server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
      show_sql: true
  main:
    web-application-type: servlet

  servlet:
    multipart:
      max-file-size: 100MB  # Maximum size for a single uploaded file
      max-request-size: 250MB  # Maximum size for a multipart request


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  key: ${JWT_KEY}
  expiry: ${JWT_EXPIRY}
