export const allowedLanguages = new Set([
  "American English",
  "Arabic",
  "Bengali",
  "Brazilian Portuguese",
  "British English",
  "Chinese",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "European Portuguese",
  "European Spanish",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Malayalam",
  "Mandarin Chinese",
  "Marathi",
  "Mexican Spanish",
  "Norwegian",
  "Odia",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Simplified Chinese",
  "Spanish",
  "Standard Arabic",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Traditional Chinese",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese"
]);
